#!/usr/bin/env python3
"""
Weekly paper pipeline queue patch — 2026-07-03 (EXP-106, EXP-107).

A800 connectivity: offline since 2026-05-14 (day 50). Apply when restored.

This patch is generated by the WEEKLY PAPER PIPELINE (not the daily ideas pipeline).
The daily pipeline added EXP-104 and EXP-105 earlier today.
This patch adds two experiments specifically addressing AAAI reviewer weaknesses
identified in review-2026-07-03.md.

Apply AFTER pending_queue_update_2026_07_03.py:
    python3 auto_research/pending_queue_update_2026_07_03.py        # EXP-104, EXP-105
    python3 auto_research/pending_queue_update_2026_07_03_paper.py  # EXP-106, EXP-107

Weaknesses addressed:
    EXP-106 → W5 (no tau2 routing baseline comparison)
    EXP-107 → W4 (disconnected tracks — no cross-domain router eval)

Queue was ~109 pending on 2026-07-03 before this patch.
"""
import json
from pathlib import Path

STATE_PATH = Path("/data0/home/zeyuwang/auto_research/state.json")

NEW_EXPERIMENTS = [
    {
        "id": "exp_2026_07_03_paper_001_tau2_random50_routing_baseline",
        "priority": 8,
        "kind": "forgetting_eval",
        "rationale": (
            "AAAI Reviewer Weakness W5: 'No comparison to routing baselines on tau2 tasks.' "
            ""
            "Current Table 7 shows: always-large=71%, always-small=80%, router=71% (hurts). "
            "An adversarial reviewer will ask: does the trained router do better than RANDOM? "
            "If random-50% routing achieves ~75-78% task pass (between always-small and "
            "always-large) at ~55% cost, but the trained router achieves 71% at 46% cost, "
            "the router is WORSE than random on held-out tau2. This would be fatal for the "
            "routing claim in §7. If random-50% achieves ~75-78%, the paper MUST compare to "
            "it and explain why the trained router underperforms. "
            ""
            "Experiment: evaluation-only run (no training). Randomly assign each of the 100 "
            "held-out tau2 tasks to small (35B) or large (GPT-5.4) with probability 0.5. "
            "Repeat 5 times with different random seeds to get mean ± std. "
            "Expected: random-50% task pass ≈ 0.5*80% + 0.5*71% = 75.5%, cost ≈ 55%. "
            "If trained router (71%) < random-50% (75.5%), we need a stronger statement in "
            "the paper: the router is trained on in-distribution traces but held-out task "
            "types shifted the difficulty distribution, causing anti-correlated routing. "
            "This is a concrete mechanism worth reporting (not hiding). "
            ""
            "Alternative baselines to add in the same run (0 extra GPU cost): "
            "  (1) always-large-on-hard: route to large if prompt length > median, else small "
            "  (2) always-small-unless-airline: route airline tasks to large (domain heuristic) "
            "These cheap baselines complete the tau2 routing baseline comparison section. "
        ),
        "spec": {
            "pipeline": "tau2_baseline_eval_only",
            "bench": "tau2_bench",
            "eval_split": "held_out_100",
            "baselines": [
                {"name": "random_50", "routing_prob_large": 0.5, "n_seeds": 5},
                {"name": "length_heuristic",
                 "routing_rule": "large if prompt_tokens > median else small"},
                {"name": "airline_heuristic",
                 "routing_rule": "large if domain==airline else small"},
            ],
            "compare_with": [
                "Table 7 trained router: 71% task pass, 66% route acc, 46% cost",
                "Table 7 always-small: 80% task pass, 10% cost",
                "Table 7 always-large: 71% task pass, 100% cost",
            ],
            "primary_metrics": [
                "task_pass_mean", "task_pass_std",
                "cost_vs_large_mean", "cost_vs_large_std",
            ],
            "target_outcome": (
                "Establish whether trained router beats random routing on held-out tau2. "
                "If not: add 1-sentence explanation in §7: router anti-correlation with "
                "held-out difficulty is expected when small model dominates on held-out. "
                "Either way: random-50% baseline is essential for AAAI Table 7. "
            ),
            "gpu": "auto",
            "estimated_gpu_hours": 0.5,
        },
        "gpu": "auto",
    },
    {
        "id": "exp_2026_07_03_paper_002_cross_domain_router_humaneval_on_tau2",
        "priority": 7,
        "kind": "forgetting_eval",
        "rationale": (
            "AAAI Reviewer Weakness W4: 'Three disconnected experimental tracks — "
            "the paper reads as four separate experiments, not a unified system.' "
            ""
            "The adversarial reviewer argument: 'HumanEval BERT router (93% accuracy on "
            "code prompts) is a completely different object from the TF-IDF+LR tau2 router "
            "(66% on held-out agentic prompts). The paper calls both a MERA router, but they "
            "have nothing in common beyond the name.' "
            ""
            "This experiment produces an EMPIRICAL BRIDGE: apply the HumanEval-trained BERT "
            "router (§4, 93.04% on 848 code examples) to the 100 held-out tau2 prompts and "
            "measure its routing accuracy against the oracle labels from Table 7. "
            ""
            "Expected result: near-chance accuracy (BERT router trained on code tasks cannot "
            "distinguish easy vs. hard agentic customer-service tasks). This confirms the "
            "paper's core claim: domain-specific routing is needed, and the BERT router "
            "designed for code generation cannot be reused for agentic tasks. "
            ""
            "This result SUPPORTS the paper's framing: MERA is a framework for routing + "
            "evolution; the specific router and model depend on the domain. The two tracks "
            "are connected by the framework, not by sharing a router binary. "
            ""
            "Secondary diagnostic: apply the tau2 TF-IDF+LR router to the 848 HumanEval "
            "code examples. Expected: also near-chance (domain-specific routing confirmed "
            "in both directions). "
            ""
            "Compute cost: near-zero — both routing evaluations are CPU inference (BERT "
            "forward passes + TF-IDF feature extraction), no GPU needed. "
            "Implementation: 1 Python script, ~50 lines. "
            ""
            "Paper impact: adds 2-3 sentences to §1 (multi-track framing) and a short "
            "paragraph to §7 or §6: 'Cross-domain routing shows that HumanEval BERT router "
            "achieves X% on tau2 held-out (near chance), confirming that routing is inherently "
            "domain-specific and MERA components do not transfer without re-training.' "
        ),
        "spec": {
            "pipeline": "cross_domain_router_eval",
            "bench": "cross_domain",
            "sub_experiments": [
                {
                    "name": "he_bert_router_on_tau2",
                    "router": "results/e2e_4cyc_gpt55/router/router.joblib",
                    "eval_data": "tau2 held-out 100 prompts",
                    "oracle_labels": "Table 7 (small=good for 80 tasks, large=good for 71 tasks, "
                                     "with overlap for 51 tasks where both agree)",
                    "expected_acc": "~50% (near chance — code BERT features irrelevant for "
                                    "agentic prompts)",
                },
                {
                    "name": "tau2_tfidf_router_on_he",
                    "router": "results/cwy_35b_joint_20260606_165203/router/router.joblib",
                    "eval_data": "HumanEval 848 routing examples",
                    "oracle_labels": "848-example routing test split from §4",
                    "expected_acc": "~50-60% (TF-IDF on agentic traces likely irrelevant for "
                                    "code task routing)",
                },
            ],
            "primary_metrics": [
                "routing_accuracy",
                "large_recall",
                "small_recall",
            ],
            "target_outcome": (
                "Cross-domain routing accuracy < 65% in both directions. "
                "This empirically validates the multi-track framing: MERA components are "
                "domain-specific and must be re-trained per domain. The framework is unified; "
                "the instantiation is domain-specific. "
            ),
            "gpu": "auto",
            "estimated_gpu_hours": 0.1,
        },
        "gpu": "cpu",
    },
]


def main() -> None:
    if not STATE_PATH.exists():
        print(f"ERROR: {STATE_PATH} not found. Is the A800 mounted?")
        raise SystemExit(1)

    with STATE_PATH.open() as f:
        state = json.load(f)

    existing_ids = {e["id"] for e in state.get("queue", [])}
    existing_ids |= {e["id"] for e in state.get("history", [])}

    added = []
    for exp in NEW_EXPERIMENTS:
        if exp["id"] in existing_ids:
            print(f"  SKIP (duplicate): {exp['id']}")
            continue
        state["queue"].append(exp)
        added.append(exp["id"])
        print(f"  QUEUED: {exp['id']}  (priority={exp['priority']}, "
              f"kind={exp['kind']})")

    if not added:
        print("No new experiments added (all duplicates).")
        return

    tmp = STATE_PATH.with_suffix(".tmp")
    with tmp.open("w") as f:
        json.dump(state, f, indent=2)
    tmp.replace(STATE_PATH)
    print(f"\nSaved {STATE_PATH}. Added {len(added)} experiment(s): {added}")


if __name__ == "__main__":
    main()
