#!/usr/bin/env python3
"""
Paper pipeline queue patch — 2026-06-19 (EXP-080, EXP-081).

Generated by weekly AAAI paper pipeline (Friday 11:00 UTC).

A800 connectivity: offline since 2026-05-14 (day 36). Apply when restored.

Apply AFTER all prior daily patches:
    python3 auto_research/pending_queue_update.py
    python3 auto_research/pending_queue_update_2026_06_06.py
    ... (all daily patches through 2026_06_19)
    python3 auto_research/pending_queue_update_2026_06_19.py    # EXP-078, EXP-079
Then apply this patch:
    python3 auto_research/pending_queue_update_2026_06_19_paper.py  # EXP-080, EXP-081

Data motivating today's proposals
----------------------------------
results/e2e_4cyc_gpt55/cycle_3/grpo_adapter/grpo_info.json (committed 2026-06-17):
    n_groups=82, n_dropped_zero_variance=43 (52.4%), n_informative_groups=39
    → DAPO G=8 reduces zero-variance from 73% (G=4 standard) but 52.4% still non-informative
    → Full system = Router system at cycle 3 (both 92.68% task pass)

results/e2e_4cyc_gpt55/final_ablation_table.md:
    Skills arm: 70.73% (cycle 0) → 75.61% (cycle 3) — positive MERA evolution signal
    Full task pass: stable around 91-93% across 4 cycles
    → Multi-seed validation needed for AAAI soundness

Paper weakness addressed:
    W1 — all LLM training results are n=1 seed (EXP-080 adds multi-seed for 4-cycle HumanEval)
    W7 — 52.4% zero-variance compared to 73% conflates G, model, and benchmark (EXP-081 isolates G)
"""
import json
import os
import tempfile
from pathlib import Path

STATE_PATH = Path("/data0/home/zeyuwang/auto_research/state.json")

_HE_EVAL = (
    "/data0/home/zeyuwang/router-skills-evolve-data/humaneval/HumanEval.jsonl.gz"
)
_MBPP_EVAL = (
    "/data0/home/zeyuwang/router-skills-evolve-data/mbpp_aug/eval100.jsonl"
)
_E2E_CONFIG = "config/humaneval_dapo_gpt.yaml"

NEW_EXPERIMENTS = [
    {
        "id": "exp_2026_06_19_003_multiseed_4cycle_humaneval_dapo",
        "priority": 9,
        "kind": "joint_cycle_multiseed",
        "rationale": (
            "Paper pipeline W1: All LLM training results are n=1 seed. The AAAI 2027 "
            "soundness score (4/10) is dominated by this weakness. EXP-038 covers "
            "MBPP single-epoch GRPO multi-seed. This experiment covers the multi-cycle "
            "HumanEval DAPO setting from e2e_4cyc_gpt55, which was committed 2026-06-17 "
            "and incorporated into paper v3 (2026-06-19). "
            "Key claims to validate: (1) skills arm improvement 70.73%→75.61% is "
            "systematic (not a lucky seed); (2) Full=Router at cycle 3 (92.68%) is "
            "systematic; (3) GRPO training with DAPO G=8 does not help routing beyond "
            "the router across seeds. Three seeds would yield SE≈±4pp at cycle-3 "
            "HumanEval task pass (82 tasks). If the skills arm improvement (4.88pp) "
            "holds across 3 seeds (consistent direction), it strengthens the MERA "
            "evolution claim materially. If it reverses, the paper must cut the claim. "
            "Wall-clock: each seed runs the full 4-cycle pipeline (~4h) = ~12 GPU-hours "
            "on 1x A800. "
            "Source: paper review W1 (review-2026-06-19.md) + grpo_info.json (commit 4778fa9)."
        ),
        "spec": {
            "pipeline": "e2e_4cyc",
            "bench": "humaneval",
            "config": _E2E_CONFIG,
            "n_cycles": 4,
            "n_seeds": 3,
            "seeds": [1, 2, 3],
            "large_model": "gpt-5.5",
            "small_model": "Qwen/Qwen3.6-35B-A3B",
            "grpo_algo": "dapo",
            "n_generations": 8,
            "max_turns": 3,
            "lora_r": 16,
            "lr": 5e-6,
            "beta": 0.04,
            "eval_data": _HE_EVAL,
            "primary_metrics": [
                "cycle3_full_task_pass",
                "cycle3_skills_arm_task_pass",
                "cycle3_grpo_n_dropped_zero_variance",
                "cycle3_routing_accuracy",
                "cycle3_cost_vs_large",
            ],
            "report": "mean_std_per_metric",
            "paper_claim": "skills arm 70.73%->75.61%, Full=Router 92.68%",
            "estimated_hours": 12.0,
            "depends_on": "e2e_4cyc_gpt55 (seed 0, reference run)",
        },
        "gpu": "auto",
    },
    {
        "id": "exp_2026_06_19_004_zero_variance_scaling_g4_g8_g16_g32_humaneval_1b5",
        "priority": 8,
        "kind": "forgetting_eval",
        "rationale": (
            "Paper pipeline W7: The 52.4% zero-variance finding (G=8 DAPO, HumanEval, "
            "Qwen3.6-35B-A3B, from grpo_info.json) is compared with the 73% finding "
            "(G=4 standard GRPO, MBPP, Qwen2.5-Coder-1.5B) in §7. These differ on "
            "three axes: G value, model size, and benchmark. An adversarial reviewer "
            "will correctly note this is not an apples-to-apples G scaling curve. "
            "This experiment fixes model=Qwen2.5-Coder-1.5B and benchmark=HumanEval "
            "while varying G={4, 8, 16, 32}, producing a clean zero-variance vs G curve. "
            "Implementation: rollout-only (no weight update, no backward pass). For each "
            "G value, run one epoch of DAPO rollout collection on HumanEval 82 tasks, "
            "record n_dropped_zero_variance from grpo_info.json. Total GPU compute: "
            "~30 min × 4 G values = ~2 GPU-hours (rollout-only is fast). "
            "Expected shape of curve: monotonically decreasing zero-variance fraction as "
            "G increases (more rollouts → more chance of mixed outcome). The curve shows "
            "where G provides diminishing returns, motivating EXP-077 (G=16 DDT). "
            "Also confirms whether the 73%→52.4% drop seen in the paper is G-driven "
            "or confounded by model/benchmark differences. "
            "This is the cheapest AAAI-relevant experiment in the queue: 2 GPU-hours, "
            "no weight updates, directly generates a publishable curve for §7. "
            "Source: paper review W7 (review-2026-06-19.md)."
        ),
        "spec": {
            "mode": "rollout_only",
            "no_weight_update": True,
            "base_model": "Qwen/Qwen2.5-Coder-1.5B-Instruct",
            "bench": "humaneval",
            "eval_data": _HE_EVAL,
            "grpo_algo": "dapo",
            "dapo_dynamic_sampling": True,
            "dapo_clip_low": 0.2,
            "dapo_clip_high": 0.5,
            "rollout": "repair",
            "max_turns": 3,
            "temperature": 1.0,
            "g_values": [4, 8, 16, 32],
            "record_per_g": [
                "n_groups",
                "n_dropped_zero_variance",
                "n_informative_groups",
                "n_rollouts_kept",
            ],
            "output": "zero_variance_vs_g_curve.json",
            "paper_claim": "zero-variance at G=4: 73% (MBPP); G=8 DAPO: 52.4% (HumanEval)",
            "estimated_hours": 2.0,
            "note": (
                "No LoRA adapter loaded (use base model). "
                "This isolates the effect of G on zero-variance, controlling for model and bench. "
                "Compare G=8 result here with grpo_info.json (43/82=52.4%) to validate "
                "that 1.5B vs 35B model difference is small."
            ),
        },
        "gpu": "auto",
    },
]


def main():
    if not STATE_PATH.exists():
        print(f"ERROR: {STATE_PATH} not found. Are you on the A800 or H200?")
        return 1
    with open(STATE_PATH) as f:
        state = json.load(f)
    queue = state.setdefault("queue", [])
    existing_ids = {e["id"] for e in queue}
    existing_ids |= {e.get("id", "") for e in state.get("history", [])}
    added, skipped = [], []
    for exp in NEW_EXPERIMENTS:
        if exp["id"] in existing_ids:
            skipped.append(exp["id"])
        else:
            queue.append(exp)
            added.append(exp["id"])
    tmp_fd, tmp_path = tempfile.mkstemp(
        dir=STATE_PATH.parent, suffix=".tmp", prefix="state_"
    )
    try:
        with os.fdopen(tmp_fd, "w") as f:
            json.dump(state, f, indent=2)
        os.replace(tmp_path, STATE_PATH)
    except Exception:
        os.unlink(tmp_path)
        raise
    print(f"Added {len(added)} experiments:")
    for eid in added:
        print(f"  + {eid}")
    if skipped:
        print(f"Skipped {len(skipped)} (already present):")
        for eid in skipped:
            print(f"  - {eid}")
    print(f"Queue now has {len(queue)} pending experiments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
